# Generated by Django 6.0.3 on 2026-03-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dance_style', models.CharField(choices=[('bharatanatyam', 'Bharatanatyam'), ('kathak', 'Kathak'), ('odissi', 'Odissi'), ('kuchipudi', 'Kuchipudi'), ('manipuri', 'Manipuri'), ('mohiniyattam', 'Mohiniyattam'), ('folk_dance', 'Folk Dance'), ('contemporary', 'Contemporary'), ('hip_hop', 'Hip Hop'), ('bollywood', 'Bollywood')], max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], max_length=20)),
                ('description', models.TextField()),
                ('duration_months', models.PositiveIntegerField(default=3)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('syllabus', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
